require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ParticipanteAtividadesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ParticipanteAtividade. As you add validations to ParticipanteAtividade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParticipanteAtividadesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all participante_atividades as @participante_atividades" do
      participante_atividade = ParticipanteAtividade.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:participante_atividades)).to eq([participante_atividade])
    end
  end

  describe "GET #show" do
    it "assigns the requested participante_atividade as @participante_atividade" do
      participante_atividade = ParticipanteAtividade.create! valid_attributes
      get :show, params: {id: participante_atividade.to_param}, session: valid_session
      expect(assigns(:participante_atividade)).to eq(participante_atividade)
    end
  end

  describe "GET #new" do
    it "assigns a new participante_atividade as @participante_atividade" do
      get :new, params: {}, session: valid_session
      expect(assigns(:participante_atividade)).to be_a_new(ParticipanteAtividade)
    end
  end

  describe "GET #edit" do
    it "assigns the requested participante_atividade as @participante_atividade" do
      participante_atividade = ParticipanteAtividade.create! valid_attributes
      get :edit, params: {id: participante_atividade.to_param}, session: valid_session
      expect(assigns(:participante_atividade)).to eq(participante_atividade)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ParticipanteAtividade" do
        expect {
          post :create, params: {participante_atividade: valid_attributes}, session: valid_session
        }.to change(ParticipanteAtividade, :count).by(1)
      end

      it "assigns a newly created participante_atividade as @participante_atividade" do
        post :create, params: {participante_atividade: valid_attributes}, session: valid_session
        expect(assigns(:participante_atividade)).to be_a(ParticipanteAtividade)
        expect(assigns(:participante_atividade)).to be_persisted
      end

      it "redirects to the created participante_atividade" do
        post :create, params: {participante_atividade: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ParticipanteAtividade.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved participante_atividade as @participante_atividade" do
        post :create, params: {participante_atividade: invalid_attributes}, session: valid_session
        expect(assigns(:participante_atividade)).to be_a_new(ParticipanteAtividade)
      end

      it "re-renders the 'new' template" do
        post :create, params: {participante_atividade: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested participante_atividade" do
        participante_atividade = ParticipanteAtividade.create! valid_attributes
        put :update, params: {id: participante_atividade.to_param, participante_atividade: new_attributes}, session: valid_session
        participante_atividade.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested participante_atividade as @participante_atividade" do
        participante_atividade = ParticipanteAtividade.create! valid_attributes
        put :update, params: {id: participante_atividade.to_param, participante_atividade: valid_attributes}, session: valid_session
        expect(assigns(:participante_atividade)).to eq(participante_atividade)
      end

      it "redirects to the participante_atividade" do
        participante_atividade = ParticipanteAtividade.create! valid_attributes
        put :update, params: {id: participante_atividade.to_param, participante_atividade: valid_attributes}, session: valid_session
        expect(response).to redirect_to(participante_atividade)
      end
    end

    context "with invalid params" do
      it "assigns the participante_atividade as @participante_atividade" do
        participante_atividade = ParticipanteAtividade.create! valid_attributes
        put :update, params: {id: participante_atividade.to_param, participante_atividade: invalid_attributes}, session: valid_session
        expect(assigns(:participante_atividade)).to eq(participante_atividade)
      end

      it "re-renders the 'edit' template" do
        participante_atividade = ParticipanteAtividade.create! valid_attributes
        put :update, params: {id: participante_atividade.to_param, participante_atividade: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested participante_atividade" do
      participante_atividade = ParticipanteAtividade.create! valid_attributes
      expect {
        delete :destroy, params: {id: participante_atividade.to_param}, session: valid_session
      }.to change(ParticipanteAtividade, :count).by(-1)
    end

    it "redirects to the participante_atividades list" do
      participante_atividade = ParticipanteAtividade.create! valid_attributes
      delete :destroy, params: {id: participante_atividade.to_param}, session: valid_session
      expect(response).to redirect_to(participante_atividades_url)
    end
  end

end
